# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 18:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=240, unique=True)),
                ('abbrev', models.CharField(max_length=10)),
                ('synonym', models.CharField(max_length=240)),
                ('cost', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('user_No', models.AutoField(primary_key=True, serialize=False)),
                ('user_ID', models.CharField(max_length=24, unique=True)),
                ('name', models.CharField(max_length=240)),
                ('email', models.CharField(max_length=240, unique=True)),
                ('institution', models.CharField(max_length=240)),
                ('trainee_stage', models.CharField(max_length=240)),
            ],
        ),
    ]
