# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-28 23:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testcalculator', '0002_auto_20170215_1954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='organization',
        ),
        migrations.DeleteModel(
            name='institution',
        ),
        migrations.DeleteModel(
            name='user',
        ),
    ]
