# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-21 01:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testcalculator', '0004_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='institution',
            field=models.TextField(max_length=300),
        ),
    ]
